baseURL: https://azuriom.com/
languageCode: "en"
defaultContentLanguageInSubdir: true
title: "Azuriom"

enableRobotsTXT: true
disableKinds: [taxonomy, term, RSS, sitemap]
disableHugoGeneratorInject: true
pygmentsUseClasses: true

params:
  twitter: Azuriom

languages:
  en:
    languageName: English
    contentDir: content/en
    params:
      code: en_US
  fr:
    languageName: Français
    contentDir: content/fr
    params:
      code: fr_FR
      twitter: AzuriomFR
  de:
    languageName: Deutsch
    contentDir: content/de
    params:
      code: de_DE
  nl:
    languageName: Nederlands
    contentDir: content/nl
    params:
      code: nl_NL
  cs:
    languageName: Čeština
    contentDir: content/cs
    params:
      code: cs_CZ
  id:
    languageName: Bahasa Indonesia
    contentDir: content/id
    params:
      code: id_ID
  zh-CN:
    languageName: 简体中文
    contentDir: content/zh-cn
    params:
      code: zh_CN
  ua:
    languageName: Українська
    contentDir: content/ua
    params:
      code: uk_UA
