[build]
command = "hugo --gc"
publish = "public"

[build.environment]
HUGO_VERSION = "0.121.1"
HUGO_UGLYURLS = "true"

[context.deploy-preview]
command = "hugo --gc -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc -b $DEPLOY_PRIME_URL"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'none'; base-uri 'self'; form-action 'self'; connect-src 'self' https://api.github.com; font-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self';"

[[redirects]]
from = "/discord"
to = "https://discord.gg/VKpSJrV"

[[redirects]]
from = "/market/*"
to = "https://market.azuriom.com/:splat"

[[redirects]]
from = "/api/download"
to = "https://market.azuriom.com/api/download"

[[redirects]]
from = "/api/updates"
to = "https://market.azuriom.com/api/updates"

[[redirects]]
from = "/install/assets/v0.2.4/img/:image"
to = "https://cdn.jsdelivr.net/gh/Azuriom/Azuriom@1.0.1/public/assets/img/games/:image"

# Redirects untranslated documentations
[[redirects]]
from = "/pl/docs/*"
to = "/en/docs/:splat"
status = 302

[[redirects]]
from = "/ru/docs/*"
to = "/en/docs/:splat"
status = 302

[[redirects]]
from = "/tr/docs/*"
to = "/en/docs/:splat"
status = 302

# Serve translated 404 pages
[[redirects]]
from = "/en/*"
to = "/en/404.html"
status = 404

[[redirects]]
from = "/fr/*"
to = "/fr/404.html"
status = 404

[[redirects]]
from = "/de/*"
to = "/de/404.html"
status = 404

[[redirects]]
from = "/nl/*"
to = "/nl/404.html"
status = 404

[[redirects]]
from = "/zh-cn/*"
to = "/zh-cn/404.html"
status = 404

[[redirects]]
from = "/pl/*"
to = "/pl/404.html"
status = 404

[[redirects]]
from = "/ru/*"
to = "/ru/404.html"
status = 404

[[redirects]]
from = "/tr/*"
to = "/tr/404.html"
status = 404

[[redirects]]
from = "/cs/*"
to = "/cs/404.html"
status = 404

[[redirects]]
from = "/uk/*"
to = "/uk/404.html"
status = 404

[[redirects]]
from = "/pt-br/*"
to = "/pt-br/404.html"
status = 404

# Redirect home page to the user language
[[redirects]]
from = "/"
to = "/fr"
conditions = { Language = ["fr"] }
force = true
status = 302

[[redirects]]
from = "/"
to = "/de"
conditions = { Language = ["de"] }
force = true
status = 302

[[redirects]]
from = "/"
to = "/nl"
conditions = { Language = ["nl"] }
force = true
status = 302

[[redirects]]
from = "/"
to = "/zh-cn"
conditions = { Language = ["zh"] }
force = true
status = 302

[[redirects]]
from = "/"
to = "/pl"
conditions = { Language = ["pl"] }
force = true
status = 302

[[redirects]]
from = "/"
to = "/ru"
conditions = { Language = ["ru"] }
force = true
status = 302

[[redirects]]
from = "/"
to = "/tr"
conditions = { Language = ["tr"] }
force = true
status = 302

[[redirects]]
from = "/"
to = "/cs"
conditions = { Language = ["cs"] }
force = true
status = 302

[[redirects]]
from = "/"
to = "/uk"
conditions = { Language = ["uk"] }
force = true
status = 302

[[redirects]]
from = "/"
to = "/pt-br"
conditions = { Language = ["pt-br"] }
force = true
status = 302

[[redirects]]
from = "/"
to = "/en"
force = true
status = 302

# Redirect pages to the user language
[[redirects]]
from = "/*"
to = "/fr/:splat"
conditions = { Language = ["fr"] }
status = 302

[[redirects]]
from = "/*"
to = "/de/:splat"
conditions = { Language = ["de"] }
status = 302

[[redirects]]
from = "/*"
to = "/nl/:splat"
conditions = { Language = ["nl"] }
status = 302

[[redirects]]
from = "/*"
to = "/zh-cn/:splat"
conditions = { Language = ["zh"] }
status = 302

[[redirects]]
from = "/*"
to = "/pl/:splat"
conditions = { Language = ["pl"] }
status = 302

[[redirects]]
from = "/*"
to = "/ru/:splat"
conditions = { Language = ["ru"] }
status = 302

[[redirects]]
from = "/*"
to = "/tr/:splat"
conditions = { Language = ["tr"] }
status = 302

[[redirects]]
from = "/*"
to = "/cs/:splat"
conditions = { Language = ["cs"] }
status = 302

[[redirects]]
from = "/*"
to = "/uk/:splat"
conditions = { Language = ["uk"] }
status = 302

[[redirects]]
from = "/*"
to = "/pt-br/:splat"
conditions = { Language = ["pt-br"] }
status = 302

[[redirects]]
from = "/*"
to = "/en/:splat"
status = 302
