[build]
command = "hugo --gc"
publish = "public"

[build.environment]
HUGO_VERSION = "0.109.0"
HUGO_UGLYURLS = "true"

[context.deploy-preview]
command = "hugo --gc -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc -b $DEPLOY_PRIME_URL"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'none'; base-uri 'self'; form-action 'self'; connect-src 'self' https://api.github.com; font-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self';"

[[redirects]]
from = "/discord"
to = "https://discord.gg/VKpSJrV"

[[redirects]]
from = "/market/*"
to = "https://market.azuriom.com/:splat"

[[redirects]]
from = "/api/download"
to = "https://market.azuriom.com/api/download"

[[redirects]]
from = "/api/updates"
to = "https://market.azuriom.com/api/updates"

[[redirects]]
from = "/install/assets/v0.2.4/img/:image"
to = "https://cdn.jsdelivr.net/gh/Azuriom/Azuriom@1.0.1/public/assets/img/games/:image"

[[redirects]]
from = "/en/*"
to = "/en/404.html"
status = 404

[[redirects]]
from = "/fr/*"
to = "/fr/404.html"
status = 404

[[redirects]]
from = "/de/*"
to = "/de/404.html"
status = 404

[[redirects]]
from = "/ru/*"
to = "/ru/404.html"
status = 404

[[redirects]]
from = "/cs/*"
to = "/cs/404.html"
status = 404

[[redirects]]
from = "/uk/*"
to = "/uk/404.html"
status = 404

[[redirects]]
from = "/pt-br/*"
to = "/pt-br/404.html"
status = 404

[[redirects]]
from = "/"
to = "/fr"
# TODO use Language when possible,
#  see https://answers.netlify.com/t/language-based-redirect-only-works-when-1-browser-language-set/4252
conditions = { Country = ["fr"] }
force = true
status = 302

[[redirects]]
from = "/"
to = "/de"
conditions = { Country = ["de"] }
force = true
status = 302

[[redirects]]
from = "/"
to = "/ru"
conditions = { Country = ["ru"] }
force = true
status = 302

[[redirects]]
from = "/"
to = "/cs"
conditions = { Country = ["cz"] }
force = true
status = 302

[[redirects]]
from = "/"
to = "/uk"
conditions = { Country = ["ua"] }
force = true
status = 302

[[redirects]]
from = "/"
to = "/pt-br"
conditions = { Country = ["br"] }
force = true
status = 302

[[redirects]]
from = "/"
to = "/en"
force = true
status = 302

[[redirects]]
from = "/*"
to = "/fr/:splat"
conditions = { Country = ["fr"] }
status = 302

[[redirects]]
from = "/*"
to = "/de/:splat"
conditions = { Country = ["de"] }
status = 302

[[redirects]]
from = "/*"
to = "/ru/:splat"
conditions = { Country = ["ru"] }
status = 302

[[redirects]]
from = "/*"
to = "/cs/:splat"
conditions = { Country = ["cz"] }
status = 302

[[redirects]]
from = "/*"
to = "/uk/:splat"
conditions = { Country = ["ua"] }
status = 302

[[redirects]]
from = "/*"
to = "/pt-br/:splat"
conditions = { Country = ["br"] }
status = 302

[[redirects]]
from = "/*"
to = "/en/:splat"
status = 302
